//
//  NoticeInteractor.swift
//  Commad
//
//  Created by 정명곤 on 12/29/23.
//  Copyright (c) 2023 commad. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NoticeBusinessLogic {
  func doSomething(request: Notice.Something.Request)
}

protocol NoticeDataStore {
  //var name: String { get set }
}

final class NoticeInteractor: NoticeBusinessLogic, NoticeDataStore {
  var presenter: NoticePresentationLogic?
  var worker: NoticeWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Notice.Something.Request) {
    worker = NoticeWorker()
    worker?.doSomeWork()
    
    let response = Notice.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
