//
//  NoticeModels.swift
//  Commad
//
//  Created by 정명곤 on 12/29/23.
//  Copyright (c) 2023 commad. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Notice {
  // MARK: Use cases
  
  enum Something {
    struct Request {
        
    }
      
    struct Response {
        
    }
      
    struct ViewModel {
        
    }
  }
}
