//
//  NoticeRouter.swift
//  Commad
//
//  Created by 정명곤 on 12/29/23.
//  Copyright (c) 2023 commad. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NoticeRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol NoticeDataPassing {
  var dataStore: NoticeDataStore? { get }
}

final class NoticeRouter: NSObject, NoticeRoutingLogic, NoticeDataPassing {
  weak var viewController: NoticeController?
  var dataStore: NoticeDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: NoticeViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: NoticeDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
