//
//  NoticePresenter.swift
//  Commad
//
//  Created by 정명곤 on 12/29/23.
//  Copyright (c) 2023 commad. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NoticePresentationLogic {
  func presentSomething(response: Notice.Something.Response)
}

final class NoticePresenter: NoticePresentationLogic {
  weak var viewController: NoticeDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Notice.Something.Response) {
    let viewModel = Notice.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
