//
//  MemberDetailPresenter.swift
//  Commad
//
//  Created by 정명곤 on 1/4/24.
//  Copyright (c) 2024 commad. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MemberDetailPresentationLogic {
    func presentAlert(response: MemberDetailModels.CheckIn.Response)
    func presentHistories(response: MemberDetailModels.MemberHistory.Response)
}

final class MemberDetailPresenter: MemberDetailPresentationLogic {
    
    
    weak var viewController: MemberDetailController?
    
    // MARK: Do something
    func presentAlert(response: MemberDetailModels.CheckIn.Response) {
        guard let history = response.history else { return }
        let viewModel = MemberDetailModels.CheckIn.ViewModel(history: history)
        print(history)
    }
    
    func presentHistories(response: MemberDetailModels.MemberHistory.Response) {
        guard let histories = response.histories else { return }
        let viewModel = MemberDetailModels.MemberHistory.ViewModel(histories: histories)
        viewController?.displayHistories(viewModel: viewModel)
    }
    
}
