//
//  MemberDetailModelsModels.swift
//  Commad
//
//  Created by 정명곤 on 1/3/24.
//  Copyright (c) 2024 commad. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MemberDetailModels {
  // MARK: Use cases
  enum History {
    struct Request {
        let member: Member
    }
      
    struct Response {
        var isEntered: Bool?
        var isError: Bool
        var message: String?
    }
      
    struct ViewModel {
        var isEntered: Bool
    }
  }
}
