//
//  MemberDetailModelsModels.swift
//  Commad
//
//  Created by 정명곤 on 1/3/24.
//  Copyright (c) 2024 commad. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MemberDetailModels {
    // MARK: Use cases
    enum MemberHistory {
        struct Request {
            let year: String
            let month: String
        }
        
        struct Response {
            var histories: [History]?
            var isError: Bool
            var message: String?
        }
        
        struct ViewModel {
            var histories: [History]
        }
    }
    
    enum CheckIn {
        struct Request {
            
        }
        
        struct Response {
            var history: History?
            var isError: Bool
            var message: String?
        }
        
        struct ViewModel {
            var history: History
        }
    }
}
