//
//  MemberDetailPresenter.swift
//  Commad
//
//  Created by 정명곤 on 1/4/24.
//  Copyright (c) 2024 commad. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MemberDetailPresentationLogic {
  func presentSomething(response: MemberDetailModels.History.Response)
}

final class MemberDetailPresenter: MemberDetailPresentationLogic {
  weak var viewController: MemberDetailController?
  
  // MARK: Do something
  
  func presentSomething(response: MemberDetailModels.History.Response) {
      let viewModel = MemberDetailModels.History.ViewModel(isEntered: true)
//      viewController?.displaySomething(viewModel: viewModel)
  }
}
